### ISSUE TITLE
OnChange fires multiple times when blurring or focusing CardNumberElement

### ISSUE THREAD

**Issue by Mootook** [recurly/react-recurly#29]
When using the provided prop onChange with <CardNumberElement />, blurring the input will fire onChange twice with a different event body.

`<CardNumberElement`
     `onChange={e => {`
         `console.log('E: ', e)`
     ` }}`
`/>`

with a filled input using test gateway card will fire twice, once with length 19 and once with length 16.

`{empty: false
length: 19
focus: true
valid: true
firstSix: "400000"
lastFour: "0325"
brand: "visa"}`

`{empty: false
length: 16
focus: true
valid: true
firstSix: "400000"
lastFour: "0325"
brand: "visa"}`

Steps to reproduce: 
1. populate a CardNumberElement with an onChange prop, log the output.

- Using react-recurly 1.0.2
- React version 16.8.3

**Comment by dbrudner** [comment]
Hey @Mootook! Thanks for reporting this issue. I think I'm seeing the same behavior you are, but just to be sure, it'd be really helpful if you could reproduce the issue and share a codesandbox (https://codesandbox.io/s/github/recurly/react-recurly/tree/master/demo?fontsize=14&hidenavigation=1&theme=dark) or something similar.

**Comment by Mootook** [comment]
@dbrudner Thanks for the follow up...here's a code sandbox with the issue isolated https://codesandbox.io/s/recurly-demo-2ppvz

**Comment by chrissrogers** [comment]
@Mootook Just a heads up that we're  tracking this bug in one of our internal support libraries, where the issue lies. We'll be fixing it there and will give a heads up here once the next version with a fix is released. In the meantime I can just suggest ensuring your listeners remain idempotent :)

**Comment by dbrudner** [comment]
@Mootook We released the fix for this yesterday. I took a peek back at the codesandbox demo you shared and the issue looks resolved. Great reporting, thanks for sharing a solid repro of the issue.

**Comment by avivshafir** [comment]
@chrissrogers why is the `onChange` method called on load?

**Comment by chrissrogers** [comment]
@avivshafir For Elements, the scope of the `change` is a bit different because it's concerned with a change of the Element state, as opposed to only the value within the Element, like it would be for an `HTMLInputElement`. React as well will call `onChange` on each keystroke, unlike the standard `HTMLInputElement` behavior.

We'd certainly consider a new event handler, like an `onValueChange`, as a feature request. Just a s well, if you'd like to bring a use-case you're trying to solve, I'd be happy to help determine a way to accomplish it.

**Comment by avivshafir** [comment]
@chrissrogers thanks, still doesn't explain why would it call `onChange` when loaded

**Comment by chrissrogers** [comment]
When an Element is instantiated, its state is blank. When it loads on a page, its state is populated. `onChange` is called because of that state change.

**Comment by avivshafir** [comment]
onChange, should be called when there is an actual user type,  
using the dispatched event how can I know if the user actually made did input some key, if I get the same event for the load and when the user cleared the input
this is making the handling of our own input state to match recurly's (for custom validation) very difficult

**Comment by QasimQureshi** [comment]
This still behaves in a bizarre manner.

I'm trying to have the user's focus shift from my `cardMonthElement` to `cardYearElement` as soon as they've typed a slash "/" or two digits.

However, it ends up firing the "change" event as soon as the month element gets focus again, which makes it impossible to reselect month again.
